Algoritmo "ImparSomaEnquanto"
// Disciplina: [Lógica de Programação]
// Professor: João Victor
// Aluna: Daniele Araújo
// Data atual: 28/09/2022
Var
cont, soma:inteiro

Inicio
cont:= 0
Enquanto (cont<=5000) faca
Se (cont mod 2 <> 0) entao
Se (cont > 1200) E (cont < 3500) entao
Escreval ("Os valores são:", cont)
Soma:= soma+cont
Fimse
Fimse
cont:= cont+1
Fimenquanto
Escreval ("O resultado da soma é:", soma)
Fimalgoritmo