Algoritmo "Decisao"
// Disciplina: [Lógica de Programação]
// Professor: João Victor
// Aluna: Daniele Araújo
// Data atual: 15/09/2022
Var
N1, N2:inteiro
Inicio
Escreval("Digite o primeiro valor")
Leia(N1)

Escreval("Digite o segundo valor")
Leia(N2)

Escreval("-----RESULTADO-----")
Se(N1>N2) então
Escreval("O maior número é:", N1)
Fimse

Se(N2>N1) então
Escreval("O maior número é:", N2)
Fimse

Se(N1=N2) então
Escreval("São iguais")
Fimse
Fimalgoritmo